LW/urls.py
from django.urls import path
from . import views
from django.conf import settings #add this
from django.conf.urls.static import static #add this

app_name = "LW"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view , name="login"),
    path('signup/', views.signup, name='signup'),
    path('classes/', views.class_list, name='class_list'),
    path('classes/<int:class_id>/subjects/', views.subject_list, name='subject_list'),
    path('subjects/<int:subject_id>/topics/', views.topic_list, name='topic_list'),
    path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    path('topics/add/', views.add_topic, name='add_topic'),
    path('', views.home, name='home'),
    #path('about/', views.about, name='about'),
    path('catalogue/', views.catalogue, name='catalogue'),
    path('faqs/', views.faq_list, name='faqs'),
    path('catalogue/<int:class_id>/', views.class_detail, name='class_detail'),
    path('about/', views.about_view, name='about'),
    #path('exercise_pdf/<int:exercise_id>/', views.exercise_pdf_view, name='exercise_pdf_view'),
    #path('tinymce/', include('tinymce.urls')),
    # path("login/", views.login_view , name="login"),
    # path('signup/', views.signup, name='signup'),
    # path('classes/', views.class_list, name='class_list'),
    # path('classes/<int:class_id>/subjects/', views.subject_list, name='subject_list'),
    # path('subjects/<int:subject_id>/topics/', views.topic_list, name='topic_list'),
    # path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    # path('topics/add/', views.add_topic, name='add_topic'),
] 

knowledgegate/urls.py
# from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from LW import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("LW/", include("LW.urls")),
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("login/", views.login_view , name="login"),
    path('signup/', views.signup, name='signup'),
    path('classes/', views.class_list, name='class_list'),
    # path('subjects/<int:subject_id>/chapters/', views.chapter_list, name='subject_chapters'),
    # path('chapters/<int:chapter_id>/topics/', views.topic_list, name='chapter_topics'),
    path('classes/<int:class_id>/subjects/', views.subject_list, name='subject_list'),
    path('subjects/<int:subject_id>/topics/', views.topic_list, name='topic_list'),
    path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    path('topics/add/', views.add_topic, name='add_topic'),
    path('tinymce/', include('tinymce.urls')),
    path('', views.home, name='home'),
    #path('about/', views.about, name='about'),
    path('catalogue/', views.catalogue, name='catalogue'),
    path('faqs/', views.faq_list, name='faqs'),
    # path('faq/', views.faqs, name='faqs'),
    path('catalogue/<int:class_id>/', views.class_detail, name='class_detail'),
    path('about/', views.about_view, name='about'),
  
    # path('classes/', views.class_list, name='class_list'),
    # path('classes/<int:class_id>/subjects/', views.subject_list, name='subject_list'),
    # path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
    # path('subjects/<int:subject_id>/topics/', views.topic_list, name='topic_list'),
    # path('topics/add/', views.add_topic, name='add_topic'),
    # path('', views.SignupPage, name='signup'),
    # path('Login/', views.LoginPage, name='Login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LW/models.py
from django.db import models
from tinymce import models as tinymce_models




class Classes(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
class Subject(models.Model):
    name = models.CharField(max_length=50)
    classes = models.ForeignKey(Classes, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
class Topic(models.Model):
    name = models.CharField(max_length=100)
    classes = models.ForeignKey(Classes, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    heading = models.CharField(max_length=100, blank=True)
    content = tinymce_models.HTMLField() 
    pdf_file = models.FileField(upload_to='pdf_files/', blank=True, null=True)
    image = models.ImageField(upload_to='topic_images/', default=None, null=True)
    points = tinymce_models.HTMLField() 
 

    def __str__(self):
        return self.name


class FAQ(models.Model):
    question = tinymce_models.HTMLField()
    answer = tinymce_models.HTMLField()

    def __str__(self):
        return self.question
    
class About(models.Model):
    content = tinymce_models.HTMLField() 
    image = models.ImageField(upload_to='about_images/', blank=True, null=True)
    right_text = tinymce_models.HTMLField() 
    # video = models.FileField(upload_to='about_videos/', blank=True, null=True)

    def __str__(self):
        return "About Us"

LW/forms.py
from django import forms
from .models import Subject, Topic, About
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class EmailAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label='Email', required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and User.objects.filter(email=username).exists():
            return username
        raise forms.ValidationError('No user found with this email.')

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name',)

class TopicForm(forms.ModelForm):
    heading = forms.CharField(max_length=100, required=False)  # Add heading field
    points = forms.CharField(widget=forms.Textarea, required=False)  # Add points field

    class Meta:
        model = Topic
        fields = ('name', 'classes', 'subject', 'content', 'image', 'heading', 'points')
    # class Meta:
    #     model = Topic
    #     fields = ('name', 'classes' , 'subject', 'content', 'image')

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ('content', 'image', 'right_text')

LW/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# from knowledgegate.LW.forms import SubjectForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView
from .models import Classes, Subject, Topic, FAQ, About
from .forms import CustomUserCreationForm, EmailAuthenticationForm, SubjectForm, TopicForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
#from .models import FAQ


def class_list(request):
   classes = Classes.objects.all()
   return render(request, 'LW/class_list.html', {'classes' : classes})

def subject_list(request, class_id):
    classes = Classes.objects.get(pk=class_id)
    subjects = Subject.objects.filter(classes=classes)
    return render(request, 'LW/subject_list.html', {'classes': classes, 'subjects': subjects})

def topic_list(request, subject_id):
    subject = Subject.objects.get(pk=subject_id)
    topics = Topic.objects.filter(subject=subject)
    return render(request, 'LW/topic_list.html', {'subject': subject, 'topics': topics})



# def chapter_list(request, subject_id):
#     subject = Subject.objects.get(pk=subject_id)
#     chapters = Chapter.objects.filter(subject=subject)
#     return render(request, 'LW/chapter_list.html', {'subject': subject, 'chapters': chapters})


def add_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('LW:topic_list', subject_id=form.cleaned_data['subject'].id)
    else:
        form = TopicForm()
    return render(request, 'LW/add_topic.html', {'form': form})


def add_subject(request, class_id):
    classes = Classes.objects.get(pk=class_id)

    if request.method == 'POST':
        form = SubjectForm(request.POST)
        if form.is_valid():
            subject = form.save(commit=False)
            subject.classes = classes
            subject.save()
            return redirect('add_topic', class_id=class_id, subject_id=subject.id)
    else:
        form = SubjectForm()

    return render(request, 'classes/add_subject.html', {'form': form, 'classes': classes})

def topic_detail(request, topic_id):
       selected_topic = get_object_or_404(Topic, id=topic_id)
       print(selected_topic.pdf_file)
       return render(request, 'LW/topic_detail.html', {'selected_topic': selected_topic})
       #return render(request, 'topic_detail.html', {'topic': topic, 'exercises': exercises})
       
    # selected_topic = get_object_or_404(Topic, id=topic_id)
    # context = {'selected_topic': selected_topic}
    # return render(request, 'topic_detail.html', context)


def about_view(request):
    about_info = About.objects.first()  # Assuming you have only one about info
    context = {'about_info': about_info}
    return render(request, 'LW/about.html', context)
# def about(request):
#     about_info = About.objects.all()
#     return render(request, 'LW/about.html', {'about_info': about_info})

def faq_list(request):
    faqs = FAQ.objects.all()
    return render(request, 'LW/faq.html', {'faqs': faqs})

def index(request):
   return render(request, "LW/index.html",)
def home(request):
    return render(request, 'LW/home.html')

# def about(request):
#     return render(request, 'LW/about.html')

def catalogue(request):
    classes = Classes.objects.all()
    return render(request, 'LW/catalogue.html', {'classes': classes})

# def faqs(request):
#     return render(request, 'LW/faq.html')
def class_detail(request, class_id):
    # Retrieve the class object based on class_id
    selected_class = Classes.objects.get(pk=class_id)
    return render(request, 'LW/class_detail.html', {'selected_class': selected_class})
# Create your views here.
# def SignupPage(request):
#    return render(request, 'Signup.html')

# def LoginPage(request):
#    return render(request, 'Login.html')
class CustomLoginView(LoginView):
    template_name = 'LW/Login.html'
    authentication_form = EmailAuthenticationForm

    def form_valid(self, form):
        """Override form_valid to add success message and redirect."""
        messages.success(self.request, 'You have successfully logged in.')
        return super().form_valid(form)

def login_view(request):
    return CustomLoginView.as_view()(request)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Log the user in after signup
            login(request, user)
            messages.success(request, 'You have successfully signed up and logged in.')
            return redirect('index')  # Replace with your desired redirection
    else:
        form = CustomUserCreationForm()
    return render(request, 'LW/Signup.html', {'form': form})

# def loginpage(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect('index')  # Replace 'home' with your desired redirection
#         else:
#             # Invalid credentials
#             error_message = 'Invalid username or password.'
#     else:
#         error_message = ''

#     return render(request, 'LW/Login.html', {'error_message': error_message})


# def signuppage(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             # Log the user in after signup
#             login(request, user)
#             return redirect('login')  # Replace with your desired redirection
#     else:
#         form = UserCreationForm()
#     return render(request, 'LW/Signup.html', {'form': form})

# def exercise_pdf_view(request, exercise_id):
#     exercise = get_object_or_404(Exercise, id=exercise_id)
#     with open(exercise.pdf_file.path, 'rb') as pdf_file:
#         response = HttpResponse(pdf_file.read(), content_type='application/pdf')
#         response['Content-Disposition'] = f'inline; filename="{exercise.name}.pdf"'
#         return response

LW/templates/LW/Catalogue.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    {% comment %} <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet"  href="{% static 'LW/style.css' %}">
    <title> {% block  page_title %} Knowledge Gate {% endblock %}  </title>
    {% block page_links %} {% endblock  %}

</head>
<body>
    <div class="conatiner">
        <div  class="row">
            <div class="col-md-4">
                <div class="thumbnail">
                  <a href="men1.jpg" target="_blank">
                    <img src="men1.jpg" alt="img1" style="width: 100%">
                    <div class="caption">
                      <p style="text-align: center; padding: 0px; padding-top: 0px;">Crew-Neck Tee in Vintage Wash</p>
                      <p style="text-align: center; padding: 0px; padding-top: 0px;"><strong>PKR 1,890</strong></p>
                      
                    </div>
                    
                  </a>
                  
                </div>
                
              </div>
        </div>
    </div>
</body>
</html>

LW/templates/LW/Login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/signup.css' %}">
</head>
<body>
    {% block content %}
    <div class="container">
        <h2>Login</h2>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Login</button>
        </form>
        <p><a href="{% url 'signup' %}">Don't have an account? Signup here</a></p>
    </div>
    {% endblock %}
</body>
</html>

LW/templates/LW/Signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Signup</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/signup.css' %}">
</head>
<body>
    {% block content %}
    <div class="container">
        <h2>Signup</h2>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="input-group">
                <label for="password1">Password</label>
                <input type="password" id="password1" name="password1" required>
            </div>
            <div class="input-group">
                <label for="password2">Confirm Password</label>
                <input type="password" id="password2" name="password2" required>
            </div>
            <button type="submit">Signup</button>
        </form>
        <p><a href="{% url 'login' %}">Already have an account? Login here</a></p>
    </div>
    {% endblock %}
</body>
</html>

{% comment %} {% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Signup</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/signup.css' %}">
</head>
<body>
    <div class="container">
        <h2>Signup</h2>
        <form method="post" action="{% url 'signup' %}" >
            {% csrf_token %}
            {{ form.username.label_tag }} {{ form.username }}
            {{ form.email.label_tag }} {{ form.email }}
            {{ form.password1.label_tag }} {{ form.password1 }}
            {{ form.password2.label_tag }} {{ form.password2 }} 
            {% comment %} <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="input-group">
                <label for="password1">Password</label>
                <input type="password" id="password1" name="password1" required>
            </div>
            <div class="input-group">
                <label for="password2">Confirm Password</label>
                <input type="password" id="password2" name="password2" required>
            </div> {% endcomment %}
            {% comment %} <button type="submit"><a href="{% url 'login' %}">Signup</a></button>
        </form>
        <p><a href="{% url 'login' %}">Already have an account? Login here</a></p>
    </div>
</body>
</html> {% endcomment %}


{% comment %} {% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet"  href="{% static 'LW/signup.css' %}">
    <title> {% block  page_title %} Knowledge Gate {% endblock %}  </title>
    {% block page_links %} {% endblock  %}

</head>
<body>
    <div class="body-background">
        <div class="container-fluid d-flex justify-content-center align-items-center h-100">
           
           <div class="card p-3 text-center py-4">
               <h4>Create account</h4>
               <div>
                   <span>Already have an account?</span>
                   <a href="#" class="text-decoration-none">Signin</a>
               </div>
               
               <div class="mt-3 px-3">
                   <input class="form-control" placeholder="Username">
               </div>
               
               <div class="input-group px-3 mt-3">
                   <input type="text" class="form-control" placeholder="First Name" aria-label="Username">
                   <span></span>
                   <input type="text" class="form-control" placeholder="Last Name" aria-label="Server">
               </div>
                
               <div class="mt-3 px-3">
                   <input class="form-control" placeholder="E-mail">
               </div>
               
               <div class="mt-3 d-grid px-3">
                   <button class="btn btn-primary btn-block btn-signup text-uppercase">
                       <span>Signup</span>
                       
                   </button>
               </div>
               
               <div class="px-3">
                   <div class="mt-2 form-check d-flex flex-row">
                   <input class="form-check-input" type="checkbox" value="" id="services">
                   <label class="form-check-label ms-2" for="services">
                     I have read and agree to the terms.
                   </label>
                 </div>
               </div>
           </div>
            
        </div> 
     </div>
</body>
</html> {% endcomment %} 

LW/templates/LW/about.html
{% extends 'LW/base.html' %}
{% load static %}
{% block page_links %}
<link rel="stylesheet" href="{% static 'LW/style.css' %}">
{% endblock  %}
{% block page_title %}
About Us
{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="about-content">
    <p>{{ about_info.content|safe }}</p>
    {% if about_info.image %}
    <div class="image-container">
      <img src="{{ about_info.image.url }}" alt="About Us Image">
    </div>
    {% endif %}
    <div class="about-text">
      <p>{{ about_info.right_text|safe }}</p>
    </div>
  </div>
</div>
{% include "LW/footer.html" %}
{% endblock %}

LW/templates/LW/add_topic.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Topic</title>
</head>
<body>
    <h1>Add Topic for {{ subject.name }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Topic</button>
    </form>
</body>
</html>

LW/templates/LW/class_detail.html
{% extends 'LW/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <title>Class Detail</title>
  <link rel="stylesheet" type="text/css" href="{% static 'LW/class_detail.css' %}">

  {% comment %} <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0"> {% endcomment %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <title>{% block page_title %}Knowledge Gate{% endblock %}</title>
 
  <!-- Add Bootstrap CSS link -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
</head>
<body>
    {% block content %}
    <div class="container">
        <div class="class-detail">
            <h1>Class Detail: {{ class.name }}</h1>
            <p>{{ class.description }}</p>
            
            <h2>Subjects</h2>
            <ul class="subject-list">
                {% for subject in class.subject_set.all %}
                    <li><a href="{% url 'subject_detail' subject.id %}">{{ subject.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endblock %}
</body>
</html>

LW/templates/LW/class_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Class List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/style1.css' %}">
</head>

<body>
    {% block content %}
    <div class="class-list-container">
        {% for classes in classes %}
            <div class="class-card">
                <img src="{% static 'LW/class' %}{{ classes.id }}.png" class="card-img-top" alt="{{ classes.name }}">
                <h2>{{ classes.name }}</h2>
                <a href="{% url 'LW:subject_list' classes.id %}" class="button">View Subjects</a>
            </div>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

LW/templates/LW/faq.html
{% extends 'LW/base.html' %}
{% load static %}
{% block page_links %}
<link rel="stylesheet"  href="{% static 'LW/style.css' %}">
{% endblock  %}

{% block page_title %}
Knowledge Gate
{% endblock  %}
{% block content %}
<div class="container mt-4">
    {% comment %} <h2>Frequently Asked Questions</h2> {% endcomment %}
    <ul class="list-group">
      {% for faq in faqs %}
      <li class="list-group-item">
        <h4>{{ faq.question|safe }}</h4>
        <p>{{ faq.answer|safe }}</p>
      </li>
      {% endfor %}
    </ul>
  </div>
{% include "LW/footer.html" %} 
{% endblock  %}

LW/templates/LW/subject_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Subject List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/style1.css' %}">
</head>
<body>
    {% block content %}
    <div class="subject-list-container">
        {% for subject in subjects %}
            <div class="subject-card">
                <h2>{{ subject.name }}</h2>
                <a href="{% url 'LW:topic_list' subject.id %}" class="button">View Topics</a>
            </div>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

LW/templates/LW/topic_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Topic Detail</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/topicdetail.css' %}">
</head>
<body>
    {% block content %}
    <div class="topic-detail-container-fluid">
        <div class="topic-detail">
            <h2>{{ selected_topic.name }}</h2>
            <p>{{ selected_topic.subject.name }} - {{ selected_topic.classes.name }}</p>
            <div class="topic-content">
                {{ selected_topic.content|safe }}
                {% comment %} <p>{{ selected_topic.points|safe }}</p> {% endcomment %}
            </div> 
            {% if selected_topic.pdf_file %}
            <div class="pdf-link">
            <a href="{{ selected_topic.pdf_file.url }}" target="_blank" Download>
            Download PDF
            </a>
            </div>
            {% endif %}
            {% if selected_topic.image %}
                <img src="{{selected_topic.image.url}}" alt="{{ selected_topic.name }}">
            {% endif %}
            {% for topic_image in selected_topic.topicimage_set.all %}
            <img src="{{ topic_image.image.url }}" alt="Topic Image" class="topic-image">
            {% endfor %}
            <div class="topic-content">
                {% comment %} {{ selected_topic.content|safe }} {% endcomment %}
                <p>{{ selected_topic.points|safe }}</p>
            </div> 

        
        </div>
    </div>
    {% endblock %}
</body>
</html>

LW/templates/LW/topic_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Topic List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/topiclist.css' %}">
</head>
<body>
    {% block content %}
    <div class="topic-list-container">
        {% for topic in topics %}
            <div class="topic-card">
                <h2>{{ topic.name }}</h2>
                <p>{{ topic.subject.name }} - {{ topic.classes.name }}</p>
                <a href="{% url 'LW:topic_detail' topic.id %}" class="button">View Details</a>
            </div>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>
    {% comment %} <div class="container">
        <h1 class="text-center my-5">Topic List</h1>
        <div class="row">
            {% for topic in topics %}
                <div class="col-md-4 mb-4">
                    <div class="topic-card">
                        <h2>{{ topic.name }}</h2>
                        <p>{{ topic.subject.name }} - {{ topic.classes.name }}</p>
                        <a href="{% url 'LW:topic_detail' topic.id %}" class="btn btn-primary btn-block">View Details</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div> {% endcomment %}
    {% comment %} <div class="topic-list-container">
        {% for topic in topics %}
            <div class="topic-card">
                <h2>{{ topic.name }}</h2>
                <p>{{ topic.subject.name }} - {{ topic.classes.name }}</p>
                <a href="{% url 'LW:topic_detail' topic.id %}" class="button">View Details</a>
            </div>
        {% endfor %}
    </div> {% endcomment %}
{% comment %} </body>
</html> {% endcomment %}

{% comment %} <!DOCTYPE html>
<html>
<head>
    <title>Topic List</title>
    <link rel="stylesheet" type="text/css" href="{% static 'LW/style1.css' %}">
    
</head>
<body>
    <div class="topic-list-container">
        {% for topic in topics %}
            <div class="topic-card">
                <h2>{{ topic.name }}</h2>
                <p>{{ topic.subject.name }} - {{ topic.classes.name }}</p>
                <div class="topic-content">
                    <p>{{ topic.content }}</p>
                </div>
                {% if topic.image %}
                    <img src="{{ topic.image.url }}" alt="{{ topic.name }}">
                {% endif %}
            </div>
        {% endfor %}
    </div>
</body>
</html> {% endcomment %}

{% comment %} <!DOCTYPE html>
<html>
<head>
    <title>Topic List</title>
</head>
<body>
    <h1>Topics for {{ subject.name }}</h1>
    <ul>
        {% for topic in topics %}
            <li>
                <h3>{{ topic.name }}</h3>
                <p>{{ topic.content }}</p>
                <img src="{{ topic.image.url }}" alt="{{ topic.name }}" width="200">
            </li>
        {% endfor %}
    </ul>
</body>
</html> {% endcomment %}